#!/bin/bash
# SPDX-FileCopyrightText: 2026 Emerson Knapp
# SPDX-License-Identifier: Apache-2.0
set -euxo pipefail

DIR="$(dirname "$(realpath "$0")")"
"$DIR"/build-ws --build-arg BASE_IMAGE="${DEVIMG}"
