#!/bin/bash
# SPDX-FileCopyrightText: 2026 Emerson Knapp
# SPDX-License-Identifier: Apache-2.0
set -euxo pipefail

CONTAINER_NAME=${CONTAINER_NAME:-${DEVIMG}}
WS=/ws

mkdir -p ~/.cache/ccache
rocker --user --x11 \
  --network host \
  --volume "$(pwd)":${WS} \
  --volume "${HOME}"/.cache/ccache:${WS}/.ccache \
  -e CCACHE_DIR=${WS}/.ccache \
  --name "${CONTAINER_NAME}" \
  "${DEVIMG}" \
  --oyr-run-arg "-w /ws --cap-add=SYS_PTRACE --security-opt seccomp=unconfined"
