#!/bin/bash
set -euxo pipefail

mkdir -p ~/.cache/ccache
rocker --user --x11 "$DEVIMG" \
  --oyr-run-arg "--name $DEVIMG -v $(pwd):/ws -v $HOME/.cache/ccache:/ws/.ccache -w /ws --cap-add=SYS_PTRACE --security-opt seccomp=unconfined"
